from picamera2 import Picamera2, Preview
import time

picam2 = Picamera2()
config = picam2.create_preview_configuration()
picam2.configure(config)
time.sleep(2)
picam2.capture_array()
print("Started")
picam2.start()
picam2.start_preview(True)
picam2.capture_array()
time.sleep(2)
print("Stop Preview")
picam2.stop_preview()
time.sleep(2)
print("Stop")
picam2.stop()
picam2.capture_array()
time.sleep(5)
print("Restarted")
picam2.start_preview(True)
picam2.start()
picam2.capture_array()
time.sleep(5)
picam2.stop_preview()